######################################################################
# Automatically generated by qmake (2.01a) ?? 2. ??? 16:55:55 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
CONFIG += qtestlib 

# Input
HEADERS += smtp.h
SOURCES += smtp.cpp
